version: "3.3"
services:
  srv:
    image: px4flightreview
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    restart: always
    network_mode: bridge
    ports:
      - 5006:5006
    environment:
      USE_PROXY: "True"
      # PORT: "5006"
      # DOMAIN: "test.ru"
    volumes:
      - ../data:/opt/service/data
      - ../config_default.ini:/opt/service/config_default.ini:ro
